# Generated by Django 3.0.7 on 2020-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='entry',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
