# Generated by Django 3.0.7 on 2020-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200818_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
